[workspace]
members = [
  "derive",
  "smear",
  "types"
]
resolver = "2"

[workspace.dependencies]
apollo-parser = "0.6"
apollo-encoder = "0.7"
codespan-reporting = "0.11"
rowan = "0.15"
strsim = "0.10"
viewit = "0.1.5"
syn = { version = "2", features = ["full"] }


[workspace.package]
version = "0.0.0"
edition = "2021"
repository = "https://github.com/al8n/smear"
homepage = "https://github.com/al8n/smear"
license = "Apache-2.0/MIT"

