[package]
name = "smear"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
description = "Blazing fast, fully spec-compliant, reusable parser combinators for standard GraphQL and GraphQL-like DSLs."


[features]
default = ["std", "smallvec", "graphql", "graphqlx"]
alloc = []
std = ["thiserror/default", "either/default", "bytes?/default", "bstr?/default", "hipstr?/default"]

cst = ["std"]
graphql = []
graphqlx = []


bytes = ["dep:bytes", "logosky/bytes"]
bstr = ["dep:bstr", "logosky/bstr"]
hipstr = ["dep:hipstr", "logosky/hipstr"]

[dependencies]
derive_more.workspace = true
either = { version = "1", default-features = false }
paste = "1"
thiserror.workspace = true
logosky.workspace = true

smallvec = { version = "1", default-features = false, features = ["const_new"], optional = true }
hipstr = { version = "0.8", default-features = false, optional = true }
bytes = { workspace = true, optional = true }
bstr = { workspace = true, optional = true }
