[package]
name = "smear-parser"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[features]
default = ["std"]
alloc = []
std = ["chumsky/default"]

bytes = ["chumsky/bytes", "dep:bytes"]

[dependencies]
chumsky.workspace = true
derive_more.workspace = true
either = { version = "1", default-features = false }
paste = "1"

bytes = { version = "1", default-features = false, optional = true }
